### ISSUE TITLE
google drive checkpoint load 

### ISSUE THREAD

**Issue by RedekopEP** [smujiang/WSIPenMarkingRemoval#3]
Hi!
Thank you very much for sharing your code!

When I am trying to evaluate your model on my data, i get the following error:
```
loading model from checkpoint
ERROR:tensorflow:Couldn't match files for checkpoint /projects/shart/digital_pathology/data/PenMarking/model/pixel2pixel_256_50cases/model-11785000
```

I have downloaded checkpoint file from google drive and put into models folder

Could you please help with solving this issue?

**Comment by smujiang** [comment]
You can search this string in your project folder, and replace the string to the directory to your model. "/projects/shart/digital_pathology/data/PenMarking/model/pixel2pixel_256_50cases/model-11785000"

**Comment by RedekopEP** [comment]
Thank you for your reply!
So does this mean that you don`t provide trained model weights? The ones that you trained on your data?

**Comment by shihuitay** [comment]
Hello! I have the same question. Do you provide your pre-trained model for us to test using our own data? I can't seem to find the model weight anywhere in the repo or Google Drive. Thank you.
